In [ ]:
#AMB2296

In [ ]:
import numpy as np
a= np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [ ]:
type(a)
np.ndarray

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [ ]:
a.size
a.shape
a.ndim


2

In [ ]:
a[1]


array([10, 11, 12, 13])

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
a[1,3]
a[1,3]=-1
a


array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [ ]:
import numpy as np
arr=np.array([2])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

[2]
1
(1,)
<class 'numpy.ndarray'>
number of dimension: 1


In [ ]:
import numpy as np
arr=np.array(2)
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

2
1
()
<class 'numpy.ndarray'>
number of dimension: 0


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

[1 2 3 4 5]
5
(5,)
<class 'numpy.ndarray'>
number of dimension: 1


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

[[1 2 3]
 [3 4 5]]
6
(2, 3)
<class 'numpy.ndarray'>
number of dimension: 2


In [ ]:
import numpy as np
arr=np.array([[2.0,1],[1,2]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

[[2. 1.]
 [1. 2.]]
4
(2, 2)
<class 'numpy.ndarray'>
number of dimension: 2


In [ ]:
import numpy as np
arr=np.array([[[1,2,8],[3,4,5],[5,6,7]]])
print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))
nd=arr.ndim
print("number of dimension:",nd)

[[[1 2 8]
  [3 4 5]
  [5 6 7]]]
9
(1, 3, 3)
<class 'numpy.ndarray'>
number of dimension: 3


In [ ]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
nd=arr.ndim
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
arr=np.array([1,2,3,4])
print(arr[0])


1


In [ ]:
print(arr[2]+arr[3])

7


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st dimension:",arr[0,1])

2nd element on 1st dimension: 2


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
arr=np.array([1,2,3,4,5])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
product=arr[1]*arr[3]
quotient=arr[4]/arr[1]
print(sum)
print(diff)
print(product)
print(quotient)


4
1
8
2.5


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
print(arr[2]+arr[3])

7


In [ ]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st dimension:",array[0,1])

2nd element on 1st dimension: 2


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[3:])
print(arr[-3:-1])
print(arr[1:6:2])

[ 8 10 12]
[ 2  4  6  8 10]
[ 8 10 12 14 16]
[12 14]
[ 4  8 12]


In [ ]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array)
print(array[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [ ]:
print(array[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8],
])
print('crop_yields array(tons):')
print(crop_yields)
print(f'\n shape:{crop_yields.shape}')
print(f'data type:{crop_yields.dtype}')
print(f'total elements:{crop_yields.size}')
print(f'dimensions:{crop_yields.ndim}')

crop_yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

 shape:(4, 5)
data type:float64
total elements:20
dimensions:2


In [ ]:
avg_yield_per_farm = np.mean(crop_yields, axis=1)
print("\nAverage yield per farm:")
print(avg_yield_per_farm)


Average yield per farm:
[13.76 11.32 15.68 11.78]


In [ ]:
Best_farm=np.argmax(avg_yield_per_farm)
print("\n Best performing farm:Farm",Best_farm+1)
print("their average yield:", round(avg_yield_per_farm[Best_farm], 2), "tons")


 Best performing farm:Farm 3
their average yield: 15.68 tons


In [ ]:
exceptional=crop_yields>15
print(exceptional)
print('\n Exceptional yields(>15):')
print(crop_yields[exceptional])

[[False False False False  True]
 [False False False False False]
 [ True False  True  True  True]
 [False False False False False]]

 Exceptional yields(>15):
[15.2 15.1 16.2 15.5 16.8]


In [ ]:
print('\nexceptional yields(>15):')
print(crop_yields[crop_yields > 15])


exceptional yields(>15):
[15.2 15.1 16.2 15.5 16.8]


In [ ]:
categories=np.where(crop_yields)